import { Router } from 'express';
import type { Pool } from 'pg';
import { isUuid } from './params.js';

/**
 * All writes here go through req.dbClient, never the pool. actorContext has
 * already opened the transaction and set lvrf.actor_person_id on this
 * client before next() was called — pool.query() would run on a different
 * connection, outside that transaction: no actor attribution, no atomicity
 * with the rest of this request. This handler never issues BEGIN, COMMIT,
 * or ROLLBACK; the middleware owns the transaction boundary and decides on
 * commit vs rollback from the response status once this handler returns.
 *
 * Creates an evidence row and links it to a value outcome in ONE
 * transaction. This was the last governed relationship with no endpoint —
 * every prior link was written by hand in psql. Separating creation from
 * linking would allow an orphaned evidence row with nothing pointing at it,
 * so both happen together or neither does.
 *
 * NOTE — DEFECT-003: value_outcome_evidence is a bare composite-key join
 * (value_outcome_id, evidence_id) with no id column and no updated_at, so it
 * carries no audit trigger (hardening.sql's audit triggers are installed
 * per-table against a primary key and an updated_at column, and this table
 * has neither). The evidence row this endpoint creates IS audited; the LINK
 * between it and the outcome is not. This endpoint cannot fix that — closing
 * the gap means giving the join table an id and an updated_at, which is a
 * schema migration, not an application change.
 */

class ValidationError extends Error {}

function isCheckViolation(err: unknown): err is { code: '23514'; message: string } {
  return (
    typeof err === 'object' &&
    err !== null &&
    'code' in err &&
    (err as { code: unknown }).code === '23514'
  );
}

function isUniqueViolation(err: unknown): err is { code: '23505'; message: string } {
  return (
    typeof err === 'object' &&
    err !== null &&
    'code' in err &&
    (err as { code: unknown }).code === '23505'
  );
}

function requireObject(value: unknown, path: string): Record<string, unknown> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new ValidationError(`${path} is required`);
  }
  return value as Record<string, unknown>;
}

function requireString(obj: Record<string, unknown>, field: string, path: string): string {
  const v = obj[field];
  if (typeof v !== 'string' || v.trim() === '') {
    throw new ValidationError(`${path}.${field} is required`);
  }
  return v;
}

function requireUuidString(obj: Record<string, unknown>, field: string, path: string): string {
  const v = requireString(obj, field, path);
  if (!isUuid(v)) {
    throw new ValidationError(`${path}.${field} must be a valid UUID`);
  }
  return v;
}

function optionalNullableString(
  obj: Record<string, unknown>,
  field: string,
  path: string,
): string | null {
  const v = obj[field];
  if (v === undefined || v === null) return null;
  if (typeof v !== 'string') {
    throw new ValidationError(`${path}.${field} must be a string or null`);
  }
  return v;
}

function optionalBoolean(
  obj: Record<string, unknown>,
  field: string,
  path: string,
  fallback: boolean,
): boolean {
  const v = obj[field];
  if (v === undefined) return fallback;
  if (typeof v !== 'boolean') {
    throw new ValidationError(`${path}.${field} must be a boolean`);
  }
  return v;
}

function requireTimestamp(obj: Record<string, unknown>, field: string, path: string): Date {
  const v = obj[field];
  if (typeof v !== 'string' || v.trim() === '') {
    throw new ValidationError(`${path}.${field} is required`);
  }
  const date = new Date(v);
  if (Number.isNaN(date.getTime())) {
    throw new ValidationError(`${path}.${field} must be a valid ISO timestamp`);
  }
  return date;
}

// provenance is where the evidence came from, in prose. A value shorter than
// this is treated the same as a blank one: an unstated origin is the failure
// this field exists to prevent. It is never auto-generated by this endpoint.
const MIN_PROVENANCE_LENGTH = 12;

function requireProvenance(obj: Record<string, unknown>, field: string, path: string): string {
  const v = requireString(obj, field, path);
  if (v.trim().length < MIN_PROVENANCE_LENGTH) {
    throw new ValidationError(
      `${path}.${field} must state where this evidence came from, in at least ${MIN_PROVENANCE_LENGTH} characters`,
    );
  }
  return v;
}

// supports is free text on value_outcome_evidence, not a Postgres enum — see
// db/schema.ts. Only these three values are understood by walkSpine.ts and
// confidenceModel.ts; a typo here would silently skip lvrf_block_ai_actual
// (it only inspects rows where supports = 'actual'). The application
// enforces what the schema does not.
const VALID_SUPPORTS = ['baseline', 'actual', 'impact_basis'] as const;

// POST /api/value-outcomes/:outcomeId/evidence — creates an evidence row and
// links it to a value outcome, in one transaction.
export function outcomeEvidenceRouter(pool: Pool): Router {
  void pool;
  const router = Router();

  router.post('/:outcomeId/evidence', async (req, res) => {
    // actorContext (mounted ahead of every router) always sets this before
    // calling next() on a mutating request, and never calls next() otherwise.
    const client = req.dbClient!;

    const outcomeId = req.params.outcomeId;
    if (!isUuid(outcomeId)) {
      res.status(400).json({ message: `invalid value outcome id: ${outcomeId}` });
      return;
    }

    try {
      const body = requireObject(req.body, 'body');

      const kind = requireString(body, 'kind', 'body');
      const summary = requireString(body, 'summary', 'body');
      const provenance = requireProvenance(body, 'provenance', 'body');
      const supports = requireString(body, 'supports', 'body');
      if (!VALID_SUPPORTS.includes(supports as (typeof VALID_SUPPORTS)[number])) {
        throw new ValidationError(
          `body.supports must be one of: ${VALID_SUPPORTS.join(', ')}`,
        );
      }
      // Required — the column default of 'medium' is a plausible value
      // nobody stated. Validated against the enum below, not just typeof.
      const confidence = requireString(body, 'confidence', 'body');
      const sourceReference = optionalNullableString(body, 'source_reference', 'body');
      const sourceVerified = optionalBoolean(body, 'source_verified', 'body', false);
      const aiSourced = optionalBoolean(body, 'ai_sourced', 'body', false);
      const simulated = optionalBoolean(body, 'simulated', 'body', false);

      // evidence_ai_requires_query enforces this at the schema; a clear 422
      // naming the missing fields beats a constraint violation.
      let researchQuery: string | null = null;
      let researchTool: string | null = null;
      if (aiSourced) {
        researchQuery = requireString(body, 'research_query', 'body');
        researchTool = requireString(body, 'research_tool', 'body');
      }

      // evidence_attestation_is_complete requires both or neither at the
      // schema; the same rule is enforced here first for a clearer 422.
      const attestedByGiven = body.attested_by_person_id !== undefined;
      const attestedAtGiven = body.attested_at !== undefined;
      if (attestedByGiven !== attestedAtGiven) {
        throw new ValidationError(
          'body.attested_by_person_id and body.attested_at must be given together or not at all',
        );
      }
      let attestedByPersonId: string | null = null;
      let attestedAt: Date | null = null;
      if (attestedByGiven) {
        attestedByPersonId = requireUuidString(body, 'attested_by_person_id', 'body');
        attestedAt = requireTimestamp(body, 'attested_at', 'body');
      }

      const actorPersonId = req.get('x-actor-person-id');
      if (!actorPersonId) {
        // actorContext already refused any mutating request without this
        // header before this handler could run. Reaching here without it
        // means that guarantee broke, not that this caller did anything wrong.
        throw new Error('x-actor-person-id missing on a request past actorContext');
      }

      // 404, not 422: a missing, soft-deleted or superseded outcome is not
      // something this call can attach evidence to at all.
      const { rows: [outcome] } = await client.query<{ id: string; institution_id: string }>(
        `SELECT id, institution_id FROM value_outcomes
          WHERE id = $1 AND deleted_at IS NULL AND superseded_by_id IS NULL`,
        [outcomeId],
      );
      if (!outcome) {
        res.status(404).json({ message: `value outcome ${outcomeId} not found` });
        return;
      }

      // Read from the database rather than hardcoding the enum's members —
      // a future migration that adds or renames a kind should not require
      // this file to be edited to notice.
      const { rows: kindRows } = await client.query<{ enumlabel: string }>(
        `SELECT e.enumlabel FROM pg_enum e
           JOIN pg_type t ON t.oid = e.enumtypid
          WHERE t.typname = 'evidence_kind'
          ORDER BY e.enumsortorder`,
      );
      const validKinds = kindRows.map((r) => r.enumlabel);
      if (!validKinds.includes(kind)) {
        res.status(422).json({ message: `body.kind must be one of: ${validKinds.join(', ')}` });
        return;
      }

      const { rows: confidenceRows } = await client.query<{ enumlabel: string }>(
        `SELECT e.enumlabel FROM pg_enum e
           JOIN pg_type t ON t.oid = e.enumtypid
          WHERE t.typname = 'confidence_level'
          ORDER BY e.enumsortorder`,
      );
      const validConfidenceLevels = confidenceRows.map((r) => r.enumlabel);
      if (!validConfidenceLevels.includes(confidence)) {
        res.status(422).json({
          message: `body.confidence must be one of: ${validConfidenceLevels.join(', ')}`,
        });
        return;
      }

      // The attestor must be a real person of record at the OUTCOME's
      // institution — not simulated, not the vendor asserting on the
      // customer's behalf. Nothing in the schema can check this; the
      // both-or-neither shape is all evidence_attestation_is_complete knows.
      if (attestedByPersonId) {
        const { rows: [attestor] } = await client.query<{ id: string }>(
          `SELECT id FROM persons
            WHERE id = $1 AND institution_id = $2 AND simulated = false AND deleted_at IS NULL`,
          [attestedByPersonId, outcome.institution_id],
        );
        if (!attestor) {
          res.status(422).json({
            message: `attested_by_person_id does not belong to institution ${outcome.institution_id}, or is simulated: ${attestedByPersonId}`,
          });
          return;
        }
      }

      // institution_id comes from the outcome, never the payload.
      const { rows: [evidence] } = await client.query<{ id: string }>(
        `INSERT INTO evidence (
           institution_id, kind, summary, provenance, source_reference,
           confidence, source_verified, ai_sourced, research_query, research_tool,
           simulated, captured_by_person_id, attested_by_person_id, attested_at
         )
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
         RETURNING id`,
        [
          outcome.institution_id, kind, summary, provenance, sourceReference,
          confidence, sourceVerified, aiSourced, researchQuery, researchTool,
          simulated, actorPersonId, attestedByPersonId, attestedAt,
        ],
      );

      // lvrf_block_ai_actual (db/hardening.sql) fires here, not on evidence
      // itself — it only judges a row once it is offered as support for a
      // specific outcome. AI-sourced, AI-assisted, simulated or
      // vendor-published evidence offered as supports = 'actual' is refused
      // with a message naming AMENDMENT-005 Article I; that refusal is
      // caught below as a check_violation and returned unchanged.
      await client.query(
        `INSERT INTO value_outcome_evidence (value_outcome_id, evidence_id, supports)
         VALUES ($1, $2, $3)`,
        [outcomeId, evidence.id, supports],
      );

      res.status(201).json({
        evidence_id: evidence.id,
        outcome_id: outcomeId,
        supports,
      });
    } catch (err) {
      if (err instanceof ValidationError) {
        res.status(422).json({ message: err.message });
        return;
      }
      // A CHECK-constraint refusal (ERRCODE check_violation, SQLSTATE 23514)
      // — including lvrf_block_ai_actual, which raises with this code — is
      // the governance gate doing its job, not a server fault. Its message
      // names the amendment and the reason — that message IS the product
      // here, so it goes to the caller unchanged, not swallowed into a
      // generic 500 or rewritten into a friendlier string.
      if (isCheckViolation(err)) {
        res.status(422).json({ message: err.message });
        return;
      }
      // A unique-constraint collision (ERRCODE unique_violation, SQLSTATE
      // 23505) is a conflict with existing state, not a server fault. 409,
      // not 500; message unchanged, same as the check_violation branch above.
      if (isUniqueViolation(err)) {
        res.status(409).json({ message: err.message });
        return;
      }
      res.status(500).json({ message: err instanceof Error ? err.message : 'unknown error' });
    }
  });

  return router;
}
